spring:
  application:
    name: LockMyTicket

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    initialization-mode: always
    initialize: true
    continue-on-error: true
