spring:
  application:
    name: LockMyTicket

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    initialization-mode: always
    initialize: true
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none> # Choose one value
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin
